services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    environment:
      - TZ=Europe/Moscow
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=alexs1234
      - DOCKER_INFLUXDB_INIT_ORG=IoT
      - DOCKER_INFLUXDB_INIT_BUCKET=IoT
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=P5AgAduLX1t8O5ZHvlykrGgbwKyiY2mlqYOTq5QFFVmWfIIVsiaXLbRy_fa77j0JV5JChNsoVgqoNanXHw3EQg==
    ports:
      - "8086:8086"
    volumes:
      - ~/influxdb2/data:/var/lib/influxdb2
      - ~/influxdb2/conf:/etc/influxdb2/
    networks:
      - influxdb-net
    restart: always
  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=8.8.8.8
      - SERVERPORT=1871 
      - PEERS=5 
      - PEERDNS=1.1.1.1 
      - INTERNAL_SUBNET=10.10.10.0 
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=false 
    volumes:
      - ~/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ~/telegraf/conf/:/etc/telegraf/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - telegraf-net
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    environment:
      - TZ=Europe/Moscow
    ports:
      - "3000:3000"
    volumes:
      - ~/grafana/data:/var/lib/grafana/
      - ~/grafana/log:/var/log/grafana/
      - ~/grafana/conf:/etc/grafana/
    links:
      - influxdb
    networks:
      - grafana-net
    restart: always
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ~/mosquitto/config:/mosquitto/config
      - ~/mosquitto/data:/mosquitto/data
      - ~/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8081:8081
    networks:
      - mosquitto-net
    restart: always
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    volumes:
      - ~/node-red/data:/data
    networks:
      - node-red-net
    restart: always
networks:
  node-red-net:
  influxdb-net:
  mosquitto-net:
  grafana-net:
  telegraf-net:
